baseURL = "https://cv.tolecnal.net/"
languageCode = "en-us"
title = "Jostein Elvaker Haande Resume"

theme = "devlite-cv"

disableRSS = true
disableSitemap = true
disable404 = true

[params]
description = "Jostein Elvaker Haande Resume"
author = "Jostein Elvaker Haande"
title = "Jostein Elvaker Haande Resume"
github_username = "tolecnal"

# Profile section
[params.profile]
name = "Jostein Elvaker Haande"
tagline = "Systems Engineer / IT Manager"
avatar = "profile.jpg"

# Contact section
[params.contact]
enable = true

[[params.contact.list]]
class = "location"
icon = "fa-location-arrow"
url = "#"
title = "Norway"

[[params.contact.list]]
class = "email"
icon = "fa-envelope"
url = "mailto:tolecnal@tolecnal.net"
title = "tolecnal@tolecnal.net"

[[params.contact.list]]
class = "phone"
icon = "fa-phone"
url = "tel:+47-928-83-632"
title = "+47 928 83 632"

[[params.contact.list]]
class = "website"
icon = "fa-globe"
url = "https://tolecnal.net"
title = "tolecnal.net"

[[params.contact.list]]
class = "linkedin"
icon = "fa-linkedin"
url = "https://www.linkedin.com/in/josteinhaande/"
title = "@josteinhaande"

[[params.contact.list]]
class = "github"
icon = "fa-github"
url = "https://github.com/tolecnal"
title = "@tolecnal"

# Skills section
[params.skills]
enable = true
title = "Expertise"

[[params.skills.list]]
title = "Problem solving"

[[params.skills.list]]
title = "Analytical"

[[params.skills.list]]
title = "Critical thinking"

[[params.skills.list]]
title = "Team player"

[[params.skills.list]]
title = "Writing documentation"

# Languages section
[params.language]
enable = true
title = "Languages"

[[params.language.list]]
language = "Norwegian"
level = "Native"

[[params.language.list]]
language = "English"
level = "Fluent"

[[params.language.list]]
language = "German"
level = "Basic"

# Experiences section
[params.experiences]
enable = true
icon = "fa-briefcase"
title = "Work experiences"

[[params.jobs.list]]
position = "Miscellanious roles"
dates = "February 2014 - Present (10 years 1 month)"
company = "ayfie AS, Oslo, Norway"
details = "<b>Systems Engineer &rarr; Senior Systems Engineer &rarr; IT Manager</b><br /> Planning and performing installations of in-house developed software to customers. Partner network training. Performing support for both end customers and partner netowrk.Responsible for IT, from hardware to software. On Premise and Cloud resources in AWS, Azure, OVH and DigitalOcean. Office 365 services. Liason with the development team."

[[params.jobs.list]]
position = "Product Consultant"
dates = "June 2008 - January 2014 (5 years 7 months)"
company = "SystemPartner International AS, Oslo, Norway"
details = "Planning and performing installations of software and hardware used in the hospitality industriy. Performing on-site hardware installations, and on-site training of staff."

[[params.jobs.list]]
position = "Bartender"
dates = "September 2006 - May 2008 (1 year 9 months)"
company = "Goggen Sportspub, Drammen, Norway"

[[params.jobs.list]]
position = "Receptionist"
dates = "March 2005 - August 2005 (6 months)"
company = "Alcudia Port Suites, Pourto del Alcudia, Spain"

[[params.jobs.list]]
position = "Waiter"
dates = "August 2002 - August 2006 (4 years)"
company = "Jonas B. Gundersen, Drammen, Norway"

# Experiences section
[params.education]
enable = true
icon = "fa-graduation-cap"
title = "Education"

[[params.school.list]]
title = "Network Engineer"
dates = "2001 - 2022"
school = "Akademiet, Drammen"
details = "Network and infrastructure planning."

[[params.school.list]]
title = "Service Electrician"
dates = "1995 - 1998"
school = "Tinius Olsen VGS"
details = "Service Electrician for office and computer equipment."

# Projects section
[params.projects]
enable = true
icon = "fa-archive"
title = "Personal Projects"
intro = "Some of my projects that I have developed and maintain. View Github for more projects."

[[params.projects.list]]
title = "wp2hugo"
url = "https://github.com/tolecnal/wp2hugo"
tagline = "A Python application that converts a WordPress WXR backup to Hugo."

[[params.projects.list]]
title = "ansible-role-pihole-doh"
url = "https://github.com/tolecnal/ansible-role-pihole-doh"
tagline = "Ansible role to deploy Pihole using Cloudflare's DNS over HTTPS."

[[params.projects.list]]
title = "ansible-role-ohmyzsh"
url = "https://github.com/tolecnal/ansible-role-ohmyzsh"
tagline = "Ansible role to deploy and configure OhMyZsh."

[[params.projects.list]]
title = "ansible-role-tmux_npm"
url = "https://github.com/tolecnal/ansible-role-tmux_npm"
tagline = "Ansible role to install and configure tmux with the TPM plugin manager, and some nice extras."

[[params.projects.list]]
title = "ansible-role-nvchad"
url = "https://github.com/tolecnal/ansible-role-nvchad"
tagline = "Ansible role to install and configure neovim with a default configuration, and required APT and Python packages."

[params.tools]
enable = true
icon = "fa-laptop"
title = "Languages and Tools"

[[params.tools.list]]
badge = "Python"
skill = "Python"
style = "flat-square"
color = "black"
logo = "Python"

[[params.tools.list]]
badge = "PowerShell"
skill = "PowerShell"
style = "flat-square"
color = "black"
logo = "PowerShell"

[[params.tools.list]]
badge = "GNU%20Bash"
skill = "Bash"
style = "flat-square"
color = "black"
logo = "gnubash"

[[params.tools.list]]
badge = "zsh"
skill = "zsh"
style = "flat-square"
color = "black"
logo = "zsh"

[[params.tools.list]]
badge = "perl"
skill = "perl"
style = "flat-square"
color = "black"
logo = "perl"

[[params.tools.list]]
badge = "Apache"
skill = "Apache"
style = "flat-square"
color = "black"
logo = "Apache"

[[params.tools.list]]
badge = "Apache Solr"
skill = "Apache Solr"
style = "flat-square"
color = "black"
logo = "apachesolr"

[[params.tools.list]]
badge = "Nginx"
skill = "Nginx"
style = "flat-square"
color = "black"
logo = "Nginx"

[[params.tools.list]]
badge = "Markdown"
skill = "Markdown"
style = "flat-square"
color = "black"
logo = "Markdown"

[[params.tools.list]]
badge = "Windows"
skill = "Windows"
style = "flat-square"
color = "black"
logo = "Windows"

[[params.tools.list]]
badge = "Linux"
skill = "Linux"
style = "flat-square"
color = "black"
logo = "Linux"

[[params.tools.list]]
badge = "macOS"
skill = "macOS"
style = "flat-square"
color = "black"
logo = "macos"

[[params.tools.list]]
badge = "Debian"
skill = "Debian"
style = "flat-square"
color = "black"
logo = "Debian"

[[params.tools.list]]
badge = "Ubuntu"
skill = "Ubuntu"
style = "flat-square"
color = "black"
logo = "Ubuntu"

[[params.tools.list]]
badge = "RedHat"
skill = "Red%20Hat"
style = "flat-square"
color = "black"
logo = "redhat"

[[params.tools.list]]
badge = "PostgreSQL"
skill = "PostgreSQL"
style = "flat-square"
color = "black"
logo = "PostgreSQL"

[[params.tools.list]]
badge = "MySQL"
skill = "MySQL"
style = "flat-square"
color = "black"
logo = "MySQL"

[[params.tools.list]]
badge = "Microsoft SQL Server"
skill = "Microsoft SQL Server"
style = "flat-square"
color = "black"
logo = "microsoftsqlserver"

[[params.tools.list]]
badge = "MongoDB"
skill = "MongoDB"
style = "flat-square"
color = "black"
logo = "MongoDB"

[[params.tools.list]]
badge = "Redis"
skill = "Redis"
style = "flat-square"
color = "black"
logo = "Redis"

[[params.tools.list]]
badge = "Icinga"
skill = "Icinga"
style = "flat-square"
color = "black"
logo = "Icinga"

[[params.tools.list]]
badge = "Active Directory"
skill = "Active Directory"
style = "flat-square"
color = "black"
logo = "ActiveDirectory"

[[params.tools.list]]
badge = "Azure AD"
skill = "Azure AD"
style = "flat-square"
color = "black"
logo = "AzureAD"

[[params.tools.list]]
badge = "Office 365"
skill = "Office 365"
style = "flat-square"
color = "black"
logo = "Office365"

[[params.tools.list]]
badge = "Docker"
skill = "Docker"
style = "flat-square"
color = "black"
logo = "Docker"

[[params.tools.list]]
badge = "Amazon AWS"
skill = "Amazon AWS"
style = "flat-square"
color = "black"
logo = "amazonaws"

[[params.tools.list]]
badge = "Amazon EC2"
skill = "Amazon EC2"
style = "flat-square"
color = "black"
logo = "amazonec2"

[[params.tools.list]]
badge = "Amazon S3"
skill = "Amazon S3"
style = "flat-square"
color = "black"
logo = "amazons3"

[[params.tools.list]]
badge = "Microsoft Azure"
skill = "Microsoft%20Azure"
style = "flat-square"
color = "black"
logo = "Microsoft-Azure"

[[params.tools.list]]
badge = "Cloudflare"
skill = "Cloudflare"
style = "flat-square"
color = "black"
logo = "Cloudflare"

[[params.tools.list]]
badge = "DigitalOcean"
skill = "DigitalOcean"
style = "flat-square"
color = "black"
logo = "DigitalOcean"

[[params.tools.list]]
badge = "VMware"
skill = "VMware"
style = "flat-square"
color = "black"
logo = "vmware"

[[params.tools.list]]
badge = "Git"
skill = "Git"
style = "flat-square"
color = "black"
logo = "git"

[[params.tools.list]]
badge = "Ansible"
skill = "Ansible"
style = "flat-square"
color = "black"
logo = "ansible"

[[params.tools.list]]
badge = "GitHub"
skill = "GitHub"
style = "flat-square"
color = "black"
logo = "GitHub"

[[params.tools.list]]
badge = "GitHub Actions"
skill = "GitHub Actions"
style = "flat-square"
color = "black"
logo = "githubactions"

[[params.tools.list]]
badge = "GitLab"
skill = "GitLab"
style = "flat-square"
color = "black"
logo = "GitLab"

[[params.tools.list]]
badge = "Jenkins"
skill = "Jenkins"
style = "flat-square"
color = "black"
logo = "jenkins"

[[params.tools.list]]
badge = "Atlassian"
skill = "Atlassian"
style = "flat-square"
color = "black"
logo = "atlassian"

[[params.tools.list]]
badge = "Jira"
skill = "Jira"
style = "flat-square"
color = "black"
logo = "jira"

[[params.tools.list]]
badge = "Vim"
skill = "Vim"
style = "flat-square"
color = "black"
logo = "vim"

[[params.tools.list]]
badge = "Neovim"
skill = "Neovim"
style = "flat-square"
color = "black"
logo = "vim"

[[params.tools.list]]
badge = "Visual Studio Code"
skill = "Visual Studio Code"
style = "flat-square"
color = "black"
logo = "visualstudiocode"

[[params.tools.list]]
badge = "WordPress"
skill = "WordPress"
style = "flat-square"
color = "black"
logo = "wordpress"

[[params.tools.list]]
badge = "Hugo"
skill = "Hugo"
style = "flat-square"
color = "black"
logo = "hugo"

[[params.tools.list]]
badge = "Adobe Lightroom Classic"
skill = "Adobe Lightroom Classic"
style = "flat-square"
color = "black"
logo = "adobelightroomclassic"

[[params.tools.list]]
badge = "Adobe Photoshop"
skill = "Adobe Photoshop"
style = "flat-square"
color = "black"
logo = "adobephotoshop"

[markup.goldmark.renderer]
unsafe= true
